### ISSUE TITLE
Changed URIs

### ISSUE THREAD

**Issue by pinygod** [hellfire1470/MarketMoneyMaker#1]
Hello! Are you still working on the project?

**Comment by hellfire1470** [comment]
Hello. No longer as a public project.

**Comment by pinygod** [comment]
Can we discuss a couple of things? I just want to create my own bot, but have some troubles... Really hope for your help, cuz your project is the best thing I ever seen with such functionality.

**Comment by hellfire1470** [comment]
sure, if you got some questions just ask.

**Comment by pinygod** [comment]
Now, when dmarket doesnt allows you to get apikey, how can you be authorized?

**Comment by hellfire1470** [comment]
the public dmarket api is down for some time yet so its not possible without a "workaround".
If you want to be authenticated you have to simulate a browser request with all the required headers and probably use the api they use themselves.
I would recommend to develop your software with bitskins instead of dmarket. They provide a more or less stable API you can use and there should be some already implemented versions of the API to use quite simply.

**Comment by pinygod** [comment]
I really need bot for dmarket, so I have no way :) How can I simulate browser request?

**Comment by hellfire1470** [comment]
Just take a look at the _GetWebResponse in DMarketAPI. The Authorization is the one returned by DMarket headers. You might also need to simulate a login.

**Comment by pinygod** [comment]
I found that it's ok to send URIs to authorized browser, but the main problem is that bot uses embedded IE browser, where I can't authorize user, so there's no way to send there post URIs. Maybe you have ideas how to send post URIs to custom browser from code?

**Comment by hellfire1470** [comment]
well i have not implemented any authentication on dmarket since they disabled the api. But you can try just to authorize with your browser an apply the Authentication key to the IE browser. This might work for some time until you need to authenticate again. I don't have any other solutions just now. But in theory it also should work with an IE Browser to Login into your account.

**Comment by pinygod** [comment]
Dmarket just works awfully in IE, you can try to log in yourself. Where I can get Authentication key to apply it in the IE browser?

**Comment by hellfire1470** [comment]
just open the debugging console of the browser and take a look at any request headers that requires an authentication

**Comment by pinygod** [comment]
Thank you, I'm authorized my app, but now I'm getting (405 Method not allowed) error when trying to buy item, but when I'm trying to get balance or other GET stuff, not POST, it works great. Have you faced with this error?

**Comment by hellfire1470** [comment]
Are you shure the buy operation requires post and not put or patch or something else?

**Comment by pinygod** [comment]
I checked, it requires patch, but I already changed the method, before I got 405 error, now I'm getting 400 error.

**Comment by pinygod** [comment]
Every operation, which requires POST or PATCH method, throws 400 bad request error. But I’m just copying data from dmarket request. I tried to use many different functions to request, include your _getwebresponse, but nothing changes

**Comment by pinygod** [comment]
I did it, I'm just so stupid and wasn't able to copy data string from browser right... Thank you very much, I'm very appreciated for your help :)
